//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeRecord.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEducation
    {
        public int EducationId { get; set; }
        public string Degree { get; set; }
        public string College { get; set; }
        public string University { get; set; }
        public Nullable<int> EmployeeId { get; set; }
    
        public virtual tblEmployeeInfo tblEmployeeInfo { get; set; }
    }
}
